'use client';
import {useMemo,useState} from 'react';
import {holdings,Holding} from '../data/portfolio';
type Quote={price:number|null,currency:string|null};
const fx:Record<string,number>={EUR:1,CAD:.64,USD:.92,AUD:.55,HKD:.118};
function group(h:Holding){if(h.category==='ETF'||h.category==='Fysiek')return 'Apart'; if((h.score??0)>=95)return 'Kernpositie'; if((h.score??0)>=90)return 'Behouden'; if((h.score??0)>=84)return 'Afbouwen'; return 'Uitstappen / watchlist'}
function cls(g:string){return g==='Kernpositie'?'core':g==='Behouden'?'keep':g==='Afbouwen'?'reduce':g.startsWith('Uit')?'exit':'keep'}
export default function Dashboard(){
 const [quotes,setQuotes]=useState<Record<string,Quote>>({}); const [manual,setManual]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(false);
 async function refresh(){setLoading(true);const syms=holdings.map(h=>h.yahoo).filter(Boolean).join(',');try{const r=await fetch('/api/quotes?symbols='+encodeURIComponent(syms));setQuotes(await r.json())}finally{setLoading(false)}}
 const rows=useMemo(()=>holdings.map(h=>{let p=quotes[h.yahoo||'']?.price??Number(manual[h.name]||0); if(h.name==='Fysiek zilver'&&p)p=p*fx.USD/31.1034768; const value=p*h.shares*(h.name==='Fysiek zilver'?1:(fx[h.currency]??1)); return {...h,p,value,g:group(h)}}),[quotes,manual]);
 const total=rows.reduce((a,r)=>a+r.value,0); const weighted=total?rows.reduce((a,r)=>a+r.value*(r.score??0),0)/total:0; const stocks=rows.filter(r=>!['ETF','Fysiek'].includes(r.category)); const selected=stocks.filter(r=>['Kernpositie','Behouden'].includes(r.g)).length;
 return <main><div className="top"><div className="title"><h1>Project Silver Phoenix</h1><p>Ultimate Master Ranking v3.0 · portefeuille-dashboard</p></div><button onClick={refresh}>{loading?'Koersen laden…':'Actuele koersen ophalen'}</button></div>
 <div className="grid"><div className="card"><div className="muted">Portefeuillewaarde</div><div className="kpi">€ {total.toLocaleString('nl-NL',{maximumFractionDigits:0})}</div></div><div className="card"><div className="muted">Gewogen Master Score</div><div className="kpi">{weighted?weighted.toFixed(1):'—'}</div></div><div className="card"><div className="muted">Individuele aandelen</div><div className="kpi">{stocks.length}</div></div><div className="card"><div className="muted">Kern + behouden</div><div className="kpi">{selected}</div></div></div>
 <section className="section two"><div className="card"><h2>Portefeuillevereenvoudiging</h2><div className="grid">{['Kernpositie','Behouden','Afbouwen','Uitstappen / watchlist'].map(g=><div key={g}><span className={'pill '+cls(g)}>{g}</span><div className="kpi">{rows.filter(r=>r.g===g).length}</div></div>)}</div></div><div className="card"><h2>Doel</h2><p className="muted">Van {stocks.length} individuele aandelen naar ongeveer 20–25. Op basis van v3.0 vallen momenteel {selected} posities in kern + behouden.</p></div></section>
 <section className="section"><h2>Holdings</h2><div className="table-wrap"><table><thead><tr><th>Rang</th><th>Bedrijf</th><th>Ticker</th><th>Aantal</th><th>Koers</th><th>Waarde €</th><th>Allocatie</th><th>Score</th><th>Doel</th><th>Selectie</th></tr></thead><tbody>{rows.sort((a,b)=>(a.rank??999)-(b.rank??999)).map(r=><tr key={r.name}><td>{r.rank??'—'}</td><td><strong>{r.name}</strong>{!r.yahoo&&<div className="error">Geen automatisch symbool</div>}</td><td>{r.ticker}</td><td>{r.shares.toLocaleString('nl-NL',{maximumFractionDigits:6})}</td><td>{r.p?r.p.toFixed(4):<input aria-label={'koers '+r.name} placeholder="handmatig" value={manual[r.name]||''} onChange={e=>setManual({...manual,[r.name]:e.target.value})}/>}</td><td>{r.value?'€ '+r.value.toLocaleString('nl-NL',{maximumFractionDigits:0}):'—'}</td><td>{total?(r.value/total*100).toFixed(2)+'%':'—'}</td><td className="score">{r.score??'—'}</td><td>{r.target!=null?(r.target*100).toFixed(1)+'%':'—'}</td><td><span className={'pill '+cls(r.g)}>{r.g}</span></td></tr>)}</tbody></table></div></section></main>
}
