import {
  buildCanadianGasEconomicDistribution,
} from "../data/multi-sector/sectors/canadian-natural-gas/scenario-builder";

import type {
  CanadianGasEconomicScenarioInput,
} from "../data/multi-sector/sectors/canadian-natural-gas/scenario-builder";

import {
  calculateExpectedFutureValue,
  calculateCycleOpportunityPrice,
} from "../data/multi-sector/cross-asset";

const tolerance = 1e-7;

function assertClose(
  actual: number,
  expected: number,
  label: string
): void {
  if (Math.abs(actual - expected) > tolerance) {
    throw new Error(
      `${label}: expected ${expected}, received ${actual}.`
    );
  }
}

// Illustrative economics only — not a real company forecast.
// Zero production keeps this test focused on valuation wiring.

function makeScenario(
  probability: number,
  realizationYears: number,
  producingAssetValueCad: number
): CanadianGasEconomicScenarioInput {
  return {
    probability,
    realizationYears,
    valuation: {
      economicProjection: {
        beginningGasProductionMmcfPerDay: 0,
        beginningLiquidsProductionBblPerDay: 0,
        beginningNetDebtCad: 0,
        beginningDilutedShares: 100_000_000,
        years: [
          {
            projectionYear: 1,
            annualBaseDeclineRate: 0,
            annualGasProductionAddedMmcfPerDay: 0,
            annualLiquidsProductionAddedBblPerDay: 0,
            realizedGasPriceCadPerMcf: 0,
            realizedLiquidsPriceCadPerBbl: 0,
            royaltiesCadPerMcfe: 0,
            operatingCostCadPerMcfe: 0,
            transportationCostCadPerMcfe: 0,
            gAndACostCadPerMcfe: 0,
            annualInterestExpenseCad: 0,
            cashTaxesCad: 0,
            sustainingCapexCad: 0,
            growthCapexCad: 0,
            dividendsCad: 0,
            shareBuybacksCad: 0,
            debtRepaymentCad: 0,
          },
        ],
      },
      producingAssetValueCad,
      undevelopedInventoryValueCad: 0,
      unbookedOptionalityValueCad: 0,
      otherAssetValueCad: 0,
    },
  };
}

const distribution =
  buildCanadianGasEconomicDistribution({
    failure: makeScenario(0.10, 5, 100_000_000),
    bear: makeScenario(0.25, 5, 500_000_000),
    base: makeScenario(0.45, 5, 1_000_000_000),
    bull: makeScenario(0.20, 3, 2_000_000_000),
  });

// 100m shares, no debt, no distributions:
// 100m assets -> CAD 1/share
// 500m assets -> CAD 5/share
// 1bn assets -> CAD 10/share
// 2bn assets -> CAD 20/share

const cases = [
  { name: "failure", expected: 1 },
  { name: "bear", expected: 5 },
  { name: "base", expected: 10 },
  { name: "bull", expected: 20 },
] as const;

for (const testCase of cases) {
  const outcome = distribution[testCase.name];

  if (!outcome.shareholderValuePerShare) {
    throw new Error(
      `${testCase.name}: missing shareholder value.`
    );
  }

  assertClose(
    outcome.shareholderValuePerShare.mid,
    testCase.expected,
    `${testCase.name} shareholder value`
  );

  console.log(
    `PASS: ${testCase.name} = CAD ${testCase.expected.toFixed(2)}/share`
  );
}

// Check independent probability-weighted expected value:
// 0.10*1 + 0.25*5 + 0.45*10 + 0.20*20 = 9.85

const expectedValue =
  calculateExpectedFutureValue(distribution);

assertClose(
  expectedValue,
  9.85,
  "Expected future shareholder value"
);

console.log(
  "PASS: Expected future value = CAD 9.85/share"
);

// Verify Bull can realize earlier than Base.

if (
  distribution.bull.realizationYears !== 3 ||
  distribution.base.realizationYears !== 5
) {
  throw new Error(
    "Scenario realization timing was not preserved."
  );
}

console.log(
  "PASS: Bull realizes in year 3, Base in year 5"
);

// Independently verify the cycle opportunity price.

const requiredReturn = 0.12;

const cyclePrice =
  calculateCycleOpportunityPrice(
    distribution,
    requiredReturn
  );

const expectedCyclePrice =
  (0.10 * 1 + 0.25 * 5 + 0.45 * 10) /
    Math.pow(1.12, 5) +
  (0.20 * 20) /
    Math.pow(1.12, 3);

assertClose(
  cyclePrice,
  expectedCyclePrice,
  "Cycle opportunity price"
);

console.log(
  `PASS: Cycle opportunity price = CAD ${cyclePrice.toFixed(4)}`
);

// -----------------------------------------------------------------------------
// Operational scenario sensitivity test
// -----------------------------------------------------------------------------

// All four scenarios use the same production, costs,
// remaining assets and initial balance sheet.
//
// Only the realized gas price changes.
//
// No dividends or buybacks are used.
// Cash generated by operations changes ending net debt,
// which changes shareholder value.

function makeGasPriceScenario(
  probability: number,
  realizationYears: number,
  gasPriceCadPerMcf: number
): CanadianGasEconomicScenarioInput {
  return {
    probability,
    realizationYears,

    valuation: {
      economicProjection: {
        beginningGasProductionMmcfPerDay: 100,
        beginningLiquidsProductionBblPerDay: 0,

        beginningNetDebtCad: 100_000_000,
        beginningDilutedShares: 100_000_000,

        years: [
          {
            projectionYear: 1,

            annualBaseDeclineRate: 0,
            annualGasProductionAddedMmcfPerDay: 0,
            annualLiquidsProductionAddedBblPerDay: 0,

            realizedGasPriceCadPerMcf:
              gasPriceCadPerMcf,

            realizedLiquidsPriceCadPerBbl: 0,

            royaltiesCadPerMcfe: 0,
            operatingCostCadPerMcfe: 1,
            transportationCostCadPerMcfe: 0,
            gAndACostCadPerMcfe: 0,

            annualInterestExpenseCad: 0,
            cashTaxesCad: 0,

            sustainingCapexCad: 0,
            growthCapexCad: 0,

            dividendsCad: 0,
            shareBuybacksCad: 0,
            debtRepaymentCad: 0,
          },
        ],
      },

      producingAssetValueCad: 500_000_000,
      undevelopedInventoryValueCad: 0,
      unbookedOptionalityValueCad: 0,
      otherAssetValueCad: 0,
    },
  };
}

const operationalDistribution =
  buildCanadianGasEconomicDistribution({
    failure: makeGasPriceScenario(0.10, 5, 1),
    bear: makeGasPriceScenario(0.25, 5, 2),
    base: makeGasPriceScenario(0.45, 5, 4),
    bull: makeGasPriceScenario(0.20, 3, 6),
  });

// Independent expected shareholder values:
//
// Annual production = 36.5m Mcf
// Operating cost = CAD 1/Mcf
//
// Gas price CAD 1 -> FCF 0m
// Gas price CAD 2 -> FCF 36.5m
// Gas price CAD 4 -> FCF 109.5m
// Gas price CAD 6 -> FCF 182.5m
//
// Starting debt = CAD 100m
// Gross asset value = CAD 500m
// Shares = 100m
//
// Shareholder values:
// Failure: (500m - 100m) / 100m = CAD 4.000
// Bear:    (500m - 63.5m) / 100m = CAD 4.365
// Base:    (500m - (-9.5m)) / 100m = CAD 5.095
// Bull:    (500m - (-82.5m)) / 100m = CAD 5.825

const operationalCases = [
  { name: "failure", expected: 4.000 },
  { name: "bear", expected: 4.365 },
  { name: "base", expected: 5.095 },
  { name: "bull", expected: 5.825 },
] as const;

for (const testCase of operationalCases) {
  const outcome =
    operationalDistribution[testCase.name];

  if (!outcome.shareholderValuePerShare) {
    throw new Error(
      `${testCase.name}: missing operational shareholder value.`
    );
  }

  assertClose(
    outcome.shareholderValuePerShare.mid,
    testCase.expected,
    `${testCase.name} operational shareholder value`
  );

  console.log(
    `PASS: Operational ${testCase.name} = CAD ${testCase.expected.toFixed(3)}/share`
  );
}

const operationalExpectedValue =
  calculateExpectedFutureValue(
    operationalDistribution
  );

const independentlyExpectedValue =
  0.10 * 4.000 +
  0.25 * 4.365 +
  0.45 * 5.095 +
  0.20 * 5.825;

assertClose(
  operationalExpectedValue,
  independentlyExpectedValue,
  "Operational expected future value"
);

console.log(
  `PASS: Operational expected future value = CAD ${operationalExpectedValue.toFixed(4)}/share`
);